name: Update Credly Badges

on:
  schedule:
    # Runs every Saturday 5:05 PM
    - cron: "5 17 * 6 *"
  workflow_dispatch: # Run workflow manually
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: m-saikiran # optional, but default will use the same from github